### ISSUE TITLE
Have multiple license options

### ISSUE THREAD

**Issue by tloubrieu-jpl** [nasa-pds/pds-template-repo-python#1]
The CALTECH disclaimer should be included. Possibly as a header of all the files (code).

APLv2 is the license is the license we should have for open source code.
JPL or CALTEH license should be an option (we need to investigate what the text of the license should be).

We also need to look if the CALTECH disclaimer is compliant with the Apache license.

**Comment by jordanpadams** [comment]
After speaking with internal JPL folks, including the Caltech notice in the NOTICE is the way to go here.
