### ISSUE TITLE
As a developer I want to baseline on acceptable Python versions

### ISSUE THREAD

**Issue by MJJoyce** [NASA-PDS/pds-template-repo-python#28]
## 💪 Motivation
We're currently mandating `Python >= 3.6` in `setup.cfg`. This covers wide range of versions. Python3.6 is also set to be marked end of life in December 2021. I'd propose that we require the latest unless there's reasons to specifically target other versions.

Thoughts?

**Comment by jordanpadams** [comment]
@MJJoyce I am OK with going with a newer(est) version. The only concern I have is if we are trying to use the latest greatest python with every app, would this be an issue with someone needing to have 5 different versions of python running on their OS?

**Comment by MJJoyce** [comment]
Hey @jordanpadams, I think we'd be looking at something like requiring `>=3.9` vs specific patch versions (e.g., `3.9.4`) so that would hopefully limit it a bit. We should probably agree that we always stick with the latest patch version since they're usually (or at least intended to be) backwards compatible.

Of course, this is sort of how it goes with Python (and other languages I suppose) and eventually you just accept it, install `pyenv` / `conda` / whatever and have 13 different versions installed 😄

**Comment by jordanpadams** [comment]
@MJJoyce 👍 sounds good
