### ISSUE TITLE
CODEOWNERS group lacks write permission to the repository

### ISSUE THREAD

**Issue by MJJoyce** [NASA-PDS/pds-template-repo-python#38]
CODEOWNERS won't work if the group(s) listed lack write perms to the repository.

**Comment by nutjob4life** [comment]
This should do it; closing. Re-open if this isn't what was expected.
![Screen Shot 2021-09-03 at 11 01 49 AM](https://user-images.githubusercontent.com/814813/132034762-c6ab455f-3f5b-4448-80ef-d0d31db016c0.png)

**Comment by jordanpadams** [comment]
also updated here: https://github.com/NASA-PDS/nasa-pds.github.io/wiki/Git-and-Github-Guide#creating-a-new-repo
